### PR TITLE
last location to localStorage

### PR DESCRIPTION
**Pull request by HerrVoennchen**
Happy Hacktoberfest,

this PR is for issue #337. Sorry for the many changes, I had prettier active. The actual changes were in lines 102-109 and 553.

If there is an error or something wrong, please let me know, I'll fix it :)

regards,

Sebastian

### CODE REVIEW

**Comment by HerrVoennchen** [comment]
Hi @rlage,

no problem, I pushed a commit containing only the changes without prettier.

regards,

Sebastian

**Comment by rlage** [comment]
@HerrVoennchen thanks! We are looking into it! =)

**Comment by rlage** [comment]
Hi @HerrVoennchen ! I saw you updated the localStorage with last_location object, but that is not what we are trying to store at this time. What we need, partially for this issue #337 , is to store the baseMap object. It is in 'CHANGE_ACTIVE_BASE_MAP' case, so I believe it would be easier for you to update your PR.

**Comment by HerrVoennchen** [comment]
Ok, just to be clear :)

I saw that mapProperties contains coordinates and baseMap. Do you want to store really only the baseMap or would it be foreseeable to store the complete mapProperties?

**Comment by rlage** [comment]
Thanks! For now, we only need the basemap itself. =)

**Comment by HerrVoennchen** [comment]
Ok, changed to BaseMap

**Comment by rlage** [comment]
Thanks for your contribution, @HerrVoennchen ! =)

**Comment by nighto** [comment]
@HerrVoennchen added your name to our [README](https://github.com/MinisterioPublicoRJ/inLoco-2.0/blob/develop/README.md) ;-)

**Comment by HerrVoennchen** [comment]
Hehe cool, thank you 😊

**Pull request merged**
